DROP TABLE IF EXISTS `learning`.`Food`;

CREATE TABLE `learning`.`Food`(
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `UserID` INTEGER UNSIGNED NOT NULL,
    `Name` VARCHAR(255) NOT NULL,
    `Price` DECIMAL(10, 2) NOT NULL,
    `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`ID`),
    INDEX `USER_ID`(`UserID`,`UpdatedAt` ASC)
);

DROP TABLE IF EXISTS `learning`.`User`;

CREATE TABLE `learning`.`User`(
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `FirstName` VARCHAR(255) NOT NULL,
    `LastName` VARCHAR(255) NOT NULL,
    `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`ID`),
    UNIQUE KEY `FirstName_UNIQUE` (`FirstName`,`LastName`)
);